version: '3.8'

services:
  app:
    image: node:17
    command: 
      - /bin/sh
      - -c
      - |
        npm install
        npm run build
    working_dir: /app
    volumes:
      - .:/app

volumes:
  app: